#!/usr/bin/env ruby
[apply]
  whitespace = nowarn
[alias]
  co = checkout
  st = status
  ci = commit
  br = branch
  staged = diff --cached
  unstaged = diff
  both = diff HEAD
  oneline = log --pretty=oneline
  amend = commit --amend
  lg = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative
  # put = push origin HEAD
  # track = !git-track
  # thanks = !git-thanks
  # workdir = !git-new-workdir
  # up = !git pull --rebase && git push
  # ignored = "!git ls-files --others --exclude-standard"
  # nb = checkout -b
  # pending = !git --no-pager log origin/master..master && echo
  # db = !sh -c 'git branch -D "$0" && git push origin ":$0"' &> /dev/null
  # missing = !sh -c 'git cherry "$0" | cut -sd + -f 2 | xargs "git show"'
  # lc = log ORIG_HEAD.. --stat --no-merges
  # conflicts = !git ls-files --unmerged | cut -c51- | sort -u | xargs $EDITOR
  # resolve = !git ls-files --unmerged | cut -c51- | sort -u | xargs git add
  # subadd = !sh -c 'git submodule add $(git config -f"$0".git/config remote.origin.url) "$0"'
[color]
  diff = auto
  status = auto
  branch = auto
  interactive = auto
  ui = auto
[color "diff"]
  meta = yellow
[merge]
  tool = opendiff
[core]
  excludesfile = /Users/Marcus/.gitignore
  legacyheaders = false
  editor = mate -w
[git-tmbundle]
  show-diff-check = yes
  gitnub-path = /Applications/Gitnub.app
  gitx-path = /Applications/GitX.app
[git-tmbundle "log"]
  limit = 1000
[pager]
  status = true
  show-branch = true
[sendemail]
  smtpserver = smtp.example.com
  aliasesfile = /Users/marcus/.gitaliases
  aliasfiletype = mailrc
  smtpuser = marcus@exceptionz.com
  smtppass = password
  smtpssl = true
[format]
  numbered = auto
[repack]
  usedeltabaseoffset = true
[push]
  default = tracking
[mirror]
  summary = true
[branch]  
  autosetuprebase = always
  autosetupmerge = true
[help]
  autocorrect = 1
[user]
	name = Marcus Wyatt
	email = marcus.wyatt@visfleet.com
[github]
	user = marcus-wyatt
	token = b0804a78cc7a12692a1c41818b6bbbb7
