#!/bin/sh
set mainfont {Monaco 13}
set textfont {Monaco 13}
set uifont {Monaco 13}
set tabstop 8
set findmergefiles 0
set maxgraphpct 50
set maxwidth 16
set cmitmode patch
set wrapcomment none
set autoselect 1
set showneartags 1
set showlocalchanges 1
set datetimeformat {%Y-%m-%d %H:%M:%S}
set limitdiffs 1
set bgcolor white
set fgcolor black
set colors {green red blue magenta darkgrey brown orange}
set diffcolors {red "#00a000" blue}
set markbgcolor #e0e0ff
set diffcontext 3
set selectbgcolor gray85
set extdifftool opendiff
set perfile_attrs 0
set geometry(main) 1665x937+5+45
set geometry(state) normal
set geometry(topwidth) 1661
set geometry(topheight) 748
set geometry(pwsash0) "870 2"
set geometry(pwsash1) "874 2"
set geometry(botwidth) 614
set geometry(botheight) 169
set permviews {}